### ISSUE TITLE
Error in contact summary tab - not compatible with only_full_group_by sql_mode

### ISSUE THREAD

**Issue by jensschuppe** [systopia/de.systopia.gdprx#14]
With `sql_mode=only_full_group_by` the consents tab on the contact summary page is not showing and the following error message pops up:

> Unable to reach the server. Please refresh this page in your browser and try again.

This is due to the query in https://github.com/systopia/de.systopia.gdprx/blob/00c6514e85b011352800813eb175c31098f94092/CRM/Gdprx/Page/SummaryTab.php#L31-L55 not including all select clause expressions without grouping functions in the group by clause.

**Comment by bjendres** [comment]
@jensschuppe could you verify that the [fix above](https://github.com/systopia/de.systopia.gdprx/commit/9e38fc958563aa0720463f499c9e3684af61d509) works?

**Comment by jensschuppe** [comment]
I do, although:

> It is recommended that the original query is fixed rather than deploying this workaround however the workaround maybe the only real solution.
> -- <cite>[The docs](https://docs.civicrm.org/dev/en/latest/framework/database/)</cite>

**Comment by bjendres** [comment]
> I do, although [...]

Sure, I know. Feel free to refactor the query, if you think it's worth the effort...
