### ISSUE TITLE
Apply option values sorting and default when creating a new GDPRX record 

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [systopia/de.systopia.gdprx#15]
Currently values for the fields consent_category, consent_source and consent_type are managed via CiviCRM option values. However sorting and default settings of those option values do not apply when creating a new GDPRX record. Sorting is done by ID and no default value is possible.

It would be good if sorting and default settings of the option group settings are applied whenever a GDPRX record is created via the UI.

**Comment by bjendres** [comment]
released with ``0.5``
