### ISSUE TITLE
Error creating new consent

### ISSUE THREAD

**Issue by gngn23** [systopia/de.systopia.gdprx#23]
I found a small bug creating a new _consent_:
* Goto contact details
* Switch to the Gdprx tab
* Add entry
* Save

This results in: Unable to reach the server. Please refresh this page in your browser and try again.

I think I found the cause, PR coming

**Comment by bjendres** [comment]
I merged your PR and released the result as ``0.7-beta1``. 

@gngn23, could you confirm that it works? If so, I'll release an ``0.7.0``
