### ISSUE TITLE
Consent tab: unescaped quotes in title attribute results in invalid HTML

### ISSUE THREAD

**Issue by gngn23** [systopia/de.systopia.gdprx#25]
Adding a double quote in consent's _note_ results in invalid HTML.

The DB fields `civicrm_value_gdpr_consent.note` and `civicrm_gdpr_terms.text_full` (fetched via `CRM_Core_DAO::executeQuery()`) are assigned to `templates/CRM/Gdprx/Page/SummaryTab.tpl` (as 'record_note' and 'record_terms_full').
Both values are used directly in title attributes:
```
      <td title="{$record.record_terms_full}">
        {$record.record_terms_name}
      </td>

      <td title="{$record.record_note}">
        {$record.record_note_short}
      </td>
```
Setting both to a string containing a double quote (e.g. _Lorem ipsum " dolor sit amet_) results in invalid HTML:
```
<td title="Lorem ipsum " dolor="" sit="" amet"="">
```
 - the title attribute is ended by the passed (and unescaped) double quote
 - so you see only the part up to the first quote as mouse-over
 - the remaining words become attributes
 - and the TD-tag ends with two double quotes
  
Passing something more elaborated (e.g. _Lorem ipsum "style="color:pink" dolor sit amet_) could change the look resulting in
```
<td title="Lorem ipsum " style="color:pink" dolor="" sit="" amet"="">
```

HTML tags are escaped (I think DAO does this for us) so you cannot add javascript - but double quotes are not .

Setting `CIVICRM_SMARTY_DEFAULT_ESCAPE` to `TRUE` in `civicrm.settings.php` would do the trick for us - as would using `htmlspecialchars()`.
Both would result in:
```
<td title="Lorem ipsum &quot;style=&quot;color:pink&quot; dolor sit amet">
```
Since the developer docs mark `CIVICRM_SMARTY_DEFAULT_ESCAPE` as ["experimental"](https://docs.civicrm.org/dev/en/latest/security/outputs/) and the comment in `civicrm.settings.php` states "should only be enabled on development sites" I think we should go for `htmlspecialchars()`.

What do you think?
Should I write a PR for this?
Or am I getting something wrong?

P.S.: Using both `htmlspecialchars()` _and_ `CIVICRM_SMARTY_DEFAULT_ESCAPE` is `TRUE` would cause double escaping:
```
<td title="Lorem ipsum &amp;quot;style=&amp;quot;color:pink&amp;quot; dolor sit amet">
```

P.P.S.: record_date_full and record_expiry_full are also used in title attributes. These are passed through `CRM_Utils_Date::customFormat()` - so I hope we're reasonably safe here.

**Comment by bjendres** [comment]
Thanks for the report @gngn23. Will you be working on this and create a PR?

**Comment by gngn23** [comment]
Yes, I will

**Comment by gngn23** [comment]
@bjendres Did you get around to check #27 ?
Is there anything else I can (or need to) do?

**Comment by bjendres** [comment]
@gngn23 this has been fixed in ``0.7.0``, too - right?

**Comment by gngn23** [comment]
since #27 has been merged: yes.

**Comment by bjendres** [comment]
> since #27 has been merged: yes.

great, thanks
