### ISSUE TITLE
Date and valid until are lost editing a consent entry

### ISSUE THREAD

**Issue by gngn23** [systopia/de.systopia.gdprx#26]
If you add an consent entry setting _Date_ and _Valid until_ and then re-edit it, both dates are lost (i.e. not prefilled in the form).
 
I seems to be caused by using CRM_Utils_Date::setDateDefaults() to set the default dates:
```
list($date_values['consent_ui_date'], $date_values['consent_ui_date_time']) = CRM_Utils_Date::setDateDefaults(
        date('Y-m-d H:i:s', strtotime($data['consent_date'])),
        'activityDateTime');
```

This results in:
```
<input id="consent_ui_date" value="12/05/2024" ...>
```
for the (invisible) date input (which gets converted to the date picker) - note the default in 'm/d/Y' format.

The time input does not get any default at all:
```
<input class="crm-form-text required crm-form-time hasTimeEntry crm-placeholder-icon" ...>
```

**I think the default needs to be 'Y-m-d H:i:s' for the date and time together (and we do not need 'consent_ui_date_time' at all.**

Just setting
```
$date_values['consent_ui_date'] = date('Y-m-d H:i:s', strtotime($data['consent_date']));
```
worked for me.

I do not know how core's `CRM_Utils_Date::setDateDefaults()` works or is supposed to work.
```
public static function setDateDefaults($mysqlDate = NULL, $formatType = NULL, $format = NULL, $timeFormat = NULL) {
  [...]
  if ($formatType) {
      // get actual format
      $params = ['name' => $formatType];
      $values = [];
      CRM_Core_DAO::commonRetrieve('CRM_Core_DAO_PreferencesDate', $params, $values);

      if ($values['date_format']) {
        $format = $values['date_format'];
      }

      if (isset($values['time_format'])) {
        $timeFormat = $values['time_format'];
      }
    }

    $dateFormat = 'm/d/Y';
    $date = date($dateFormat, strtotime($mysqlDate));

    if (!$timeFormat) {
      $timeFormat = $config->timeInputFormat;
    }

    [...]

    return [$date, $time];
  }
```

It smells kind of funny that 
- if we pass a $formatType
- $format is set - but never used!
- and $dateFormat is set to 'm/d/Y' anyway
  ($timeFormat set from $formatType and only overwritten if empty)

So I do not know if the code should use `CRM_Utils_Date::setDateDefaults() ` at all.

Like I mentioned before I am still new to CiviCRM -- so what am I missing?

If you like I can provide a PR to set both date / time combos.

**Comment by bjendres** [comment]
Thanks for the report @gngn23. Will you be working on this and create a PR?

**Comment by gngn23** [comment]
Yes, I will

**Comment by gngn23** [comment]
PR #28

**Comment by gngn23** [comment]
@bjendres Did you get around to check #28 ?
Is there anything else I can (or need to) do?

**Comment by bjendres** [comment]
> @bjendres Did you get around to check #28 ? Is there anything else I can (or need to) do?

Yes, thanks. I created a new release "HERE":https://github.com/systopia/de.systopia.gdprx/releases/tag/0.7-beta2, could you verify that it works as expected?

@gngn23 If I get an OK from you, I'll release a ``0.7.0`` in two weeks' time.
